### ISSUE TITLE
Flag : experimental-wasm-bigint

### ISSUE THREAD

**Issue by maxtremblay** [grain-lang/grain#883] opened 2021-09-08 02:08 UTC
Hello, I just built grain from source on Arch Linux using Node v16.8.0 and yarn v1.22.11. 
I have a warning when I run the `grain` command
```
Error: unrecognized flag --experimental-wasm-bigint
```
Everything seems to work fine, but this message is a bit annoying. I removed the flag [here](https://github.com/grain-lang/grain/blob/2a5ec3db84be3533ea707c4b5118f81b4f0c1be7/cli/bin/grain.js#L13), and it resolved the problem. 

So, not a big deal for me, but I post it here in case you want to remove that in future releases. Also asking in case that flag is essential, and I broke something by removing it.

**Comment by phated** [comment] 2021-09-09 19:32
We still support node 14, where this flag is required. Maybe we can wrap it in an if statement depending on node major 🤔

**Comment by phated** [comment] 2021-09-09 19:32
Also, this seems to be a duplicate of https://github.com/grain-lang/grain/issues/114

**Closed** 2021-09-20 17:13 UTC
