### ISSUE TITLE
Feature Request/Discussion - Pipeline Operator

### ISSUE THREAD

**Issue by Simerax** [grain-lang/grain#1434] opened 2022-09-06 23:59 UTC
I just recently stumbled across this project so I don't know if this is something that would fit in the language but I thought ill just open a discussion about it since I have not found any reference to "pipe operator" in the issues here.

Issue #671 raises the question to reorder parameters to stdlib functions to be more readable by moving the data parameter to the first parameter instead of the last. This change could also give room to a pipeline operator (for example how it exists in elixir `|>`).

In case you are not familiar with what it does: It takes the value on the left and passes it as the first argument to the function on the right.

```
let words = String.split(String.replace(String.trimEnd(String.trimStart(input)), "  ", " "), " ")

// could be rewritten as
let words =  String.trimStart(input) 
             |> String.trimEnd() 
             |> String.replace("  ", " ") 
             |> String.split(" ")
```

Under the hood the compiler would just "rewrite" the pipline version back into the first nested version.
The nice thing about the pipline is that it is easy to recognize when which step happens. It just happens top to bottom instead of the first version where it is from the middle outwards and its hard to keep track which parameter belongs to which function call.

The pipeline operator also makes it trivial to insert or remove parts of the "pipeline" it is very obvious where to insert or remove a function call.

```
let words =  String.trimStart(input) 
             |> String.trimEnd() 
             // |> String.replace("  ", " ")  // commented out for testing, easy to do
             |> String.split(" ")
```

The operator could (probably) already be implemented without problems but for it to really feel like part of the language the stdlib would need to also support it. Otherwise modules like `List` or `String` would feel out of place because right now you are unable to chain them together using a pipeline.

**Comment by phated** [comment] 2022-09-07 00:01
@Simerax Thanks for your interest. This is actually a duplicate of https://github.com/grain-lang/grain/issues/403 - can you add your feedback to that thread?

**Comment by Simerax** [comment] 2022-09-07 00:01
oh wow should have searched for "|>" instead of "pipe" i guess

**Closed by phated** 2022-09-07 00:01 UTC
